import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "../styles/style.sass";

const primaryFont = Nunito({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--primary-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${primaryFont.variable} antialiased`}>{children}</body>
    </html>
  );
}
